FROM eclipse-temurin:21-jdk
MAINTAINER Piotr Minkowski <piotr.minkowski@gmail.com>
ADD target/customer-service.jar customer-service.jar
ENTRYPOINT ["java", "-jar", "/customer-service.jar"]
EXPOSE 3333
